##
## Copyright (c) 2024 TUM Department of Electrical and Computer Engineering.
##
## This file is part of ISAAC Toolkit.
## See https://github.com/tum-ei-eda/isaac-toolkit.git for further info.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
name: MLonMCU Examples
on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    # runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8"]
        mlonmcu-ref: ["main"]
        mlonmcu-template: ["dev"]
        prog: ["toycar"]
        toolchain: ["gcc"]
        simulator: ["etiss"]
        backend: ["tvmaotplus"]
        # full: ["1"]
    env:
      INSTALL_DIR: ${{ github.workspace }}/examples/standalone/install
      VENV_DIR: ${{ github.workspace }}/venv
      PYTHONPATH: ${{ github.workspace }}
      MLONMCU_HOME: ${{ github.workspace }}/workspace
      PROG: ${{ matrix.prog }}
      SIMULATOR: ${{ matrix.simulator }}
      TOOLCHAIN: ${{ matrix.toolchain }}
      BACKEND: ${{ matrix.backend }}
      # FULL: ${{ matrix.full }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # TODO: caching
    - name: Install APT packages
      run: |
        sudo apt -qq install -y build-essential git cmake libboost-system-dev libboost-filesystem-dev libboost-program-options-dev kcachegrind graphviz-dev
    - name: Initialize Virtualenv
      run: |
        python -m pip install --upgrade pip
        python -m venv $VENV_DIR
    - name: Install dependencies
      run: |
        source $VENV_DIR/bin/activate
        pip install -r requirements.txt
        pip install git+https://github.com/tum-ei-eda/mlonmcu.git@${{ matrix.mlonmcu-ref }}
    - name: Setup MLonMCU
      run: |
        source $VENV_DIR/bin/activate
        mlonmcu init $MLONMCU_HOME -t ${{ matrix.mlonmcu-template}} --non-interactive --clone-models --allow-exists
        mlonmcu setup -g
        pip install -r $MLONMCU_HOME/requirements_addition.txt
        mlonmcu setup -v --progress
    - name: Run MLonMCU example
      working-directory: examples/mlonmcu
      run: |
        source $VENV_DIR/bin/activate
        export SESS=$(pwd)/sess
        ./mlonmcu_example.sh $SESS $PROG $TOOLCHAIN $SIMULATOR $BACKEND
    - name: Archive reports
      uses: actions/upload-artifact@v4
      with:
        name: results-${{ matrix.mlonmcu-ref }}-${{ matrix.mlonmcu-template }}-${{ matrix.program }}-${{ matrix.toolchain }}-${{ matrix.simulator }}-${{ matrix.backend }}
        path: |
          examples/mlonmcu/sess/
          examples/mlonmcu/*.pdf
          examples/mlonmcu/*.out
          !examples/mlonmcu/sess/elf
          !examples/mlonmcu/sess/instr_trace/
