##
## Copyright (c) 2024 TUM Department of Electrical and Computer Engineering.
##
## This file is part of ISAAC Toolkit.
## See https://github.com/tum-ei-eda/isaac-toolkit.git for further info.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
---
name: Standalone Examples
on:
  workflow_dispatch:

jobs:
  coremark:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
        toolchain: ["gcc", "llvm"]
        # simulator: ["etiss", "etiss_perf", "spike", "spike_bm", "qemu_user", "tgc"]
        # TODO: rename to dbt-risce-riscv
        # simulator: ["etiss", "spike", "spike_bm"]
        simulator: ["etiss"]
        optimize: ["3"]
        # TODO: update gnu version & llvm version
        config:
          - {arch: "rv32im_zicsr_zifencei", abi: "ilp32", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32, etiss_version: "v0.11.2", etiss_arch: "RV32IMACFD"}
          - {arch: "rv32gc", abi: "ilp32d", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32, etiss_version: "v0.11.2", etiss_arch: "RV32IMACFD"}
          - {arch: "rv64gc", abi: "lp64d", gnu_name: "riscv64-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 64, etiss_version: "v0.11.2", etiss_arch: "RV64IMACFD"}
        # include:
        #   # - python-version: ["3.10"]
        #   #   toolchain: ["gcc"]
        #   #   simulator: ["etiss_perf"]
        #   #   config: {arch: "rv32im_zicsr_zifencei", abi: "ilp32", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32, etiss_perf_version: "", etiss_arch: "RV32IMACFD", perf_model: "cv32e40p"}
        #   # - python-version: ["3.10"]
        #   #   toolchain: ["gcc"]
        #   #   simulator: ["etiss_perf"]
        #   #   config: {arch: "rv64im_zicsr_zifencei", abi: "lp64", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 64, etiss_perf_vesion: "", etiss_arch: "RV64IMACFD", perf_model: "cva6"}
        #   - python-version: ["3.10"]
        #     toolchain: ["gcc"]
        #     simulator: ["spike_bm"]
        #     config: {arch: "rv32im_zve32x_zicsr_zifencei", abi: "ilp32", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32}
        #   - python-version: ["3.10"]
        #     toolchain: ["gcc"]
        #     simulator: ["spike_bm"]
        #     config: {arch: "rv32gcv", abi: "ilp32d", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32}
        #   - python-version: ["3.10"]
        #     toolchain: ["gcc"]
        #     simulator: ["spike_bm"]
        #     config: {arch: "rv64gcv", abi: "lp64d", gnu_name: "riscv64-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 64}
        #   # - python-version: ["3.10"]
        #   #   toolchain: ["gcc"]
        #   #   simulator: ["qemu_user"]
        #   #   config: {arch: "rv32im_zve32x_zicsr_zifencei", abi: "ilp32", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32}
          # - python-version: ["3.10"]
          #   toolchain: ["gcc"]
          #   simulator: ["qemu_user"]
          #   config: {arch: "rv32gcv", abi: "ilp32d", gnu_name: "riscv32-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 32}
          # - python-version: ["3.10"]
          #   toolchain: ["gcc"]
          #   simulator: ["qemu_user"]
          #   config: {arch: "rv64gcv", abi: "lp64d", gnu_name: "riscv64-unknown-elf", gnu_version: "2024.09.03", llvm_version: "19.1.1", xlen: 64}
    env:
      INSTALL_DIR: ${{ github.workspace }}/examples/standalone/install
      OUT_DIR: ${{ github.workspace }}/examples/standalone/out
      VENV_DIR: ${{ github.workspace }}/venv
      PYTHONPATH: ${{ github.workspace }}
      SIMULATOR: ${{ matrix.simulator }}
      TOOLCHAIN: ${{ matrix.toolchain }}
      RISCV_ARCH: ${{ matrix.config.arch }}
      RISCV_ABI: ${{ matrix.config.abi }}
      RISCV_NAME: ${{ matrix.config.gnu_name }}
      RISCV_PREFIX: ${{ github.workspace }}/examples/standalone/install/gnu
      OPTIMIZE: ${{ matrix.optimize }}
      SPIKE: ${{ github.workspace }}/examples/standalone/install/spike/bin/spike
      PK: ${{ github.workspace }}/examples/standalone/install/gnu/bin/pk_${{ matrix.config.arch }}_${{ matrix.config.abi }}
      HTIF: ${{ github.workspace }}/examples/standalone/install/gnu/bin/htif_${{ matrix.config.arch }}_${{ matrix.config.abi }}
      ETISS: ${{ github.workspace }}/examples/standalone/install/etiss/install/bin/run_helper.sh
      ETISS_INI: ${{ github.workspace }}/examples/standalone/install/etiss/install/custom.ini
      ETISS_JIT: ${{ matrix.config.etiss_jit }}
      # PERF_MODEL: ?
      # ETISS_PERF: ?
      # ETISS_PERF_INI: ?
      # ETISS_PERF_INI2: ?
      # FIVP_SDK_DIR: ?
      # FIVP_SDK_TARGET: ?
      # TGC_BSP_DIR: ?
      # TGC_SRC_DIR: ?
      # TGC_BUILD_DIR: ?
      # TGC_INSTALL_DIR: ?
      # TGC_BACKEND: ?

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    # TODO: caching
    - name: Install APT packages
      run: |
        sudo apt -qq install -y build-essential git cmake libboost-system-dev libboost-filesystem-dev libboost-program-options-dev kcachegrind graphviz-dev
    - name: Initialize Virtualenv
      run: |
        python -m pip install --upgrade pip
        python -m venv $VENV_DIR
    - name: Install dependencies
      run: |
        source $VENV_DIR/bin/activate
        pip install -r requirements.txt
    - name: Setup dependencies
      working-directory: examples/standalone
      run: |
        ./scripts/download_helper.sh $RISCV_PREFIX gnu ${{ matrix.config.gnu_version }} ${{ matrix.config.arch }}_${{ matrix.config.abi }} ${{ matrix.config.gnu_name }}

        if [[ "$TOOLCHAIN" == "llvm" ]]
        then
            ./scripts/download_helper.sh $INSTALL_DIR/llvm/ llvm ${{ matrix.config.llvm_version }}
        fi

        if [[ "$SIMULATOR" == "qemu_user" ]]
        then
            sudo apt -qq install -y qemu-user
        fi

        if [[ "$SIMULATOR" == "etiss" ]]
        then
            ./scripts/download_helper.sh $INSTALL_DIR/etiss etiss ${{ matrix.config.etiss_version }}
            ./scripts/setup_etiss_examples.sh $INSTALL_DIR/etiss_riscv_examples
            # ./scripts/setup_etiss.sh $INSTALL_DIR/etiss ${{ matrix.config.etiss_version }}
        fi

        if [[ "$SIMULATOR" == "etiss_perf" ]]
        then
            ./scripts/download_helper.sh $INSTALL_DIR/etiss_perf etiss_perf ${{ matrix.config.etiss_perf_version }}
            ./scripts/setup_etiss_examples.sh $INSTALL_DIR/etiss_riscv_examples
            # ./scripts/setup_etiss.sh $INSTALL_DIR/etiss ${{ matrix.config.etiss_perf_version }}
        fi

        if [[ "$SIMULATOR" == "tgc" ]]
        then
            # ./scripts/download_helper.sh $INSTALL_DIR/tgc tgc ${{ matrix.config.tgc_version }}
            ./scripts/setup_tgc.sh $INSTALL_DIR/tgc ${{ matrix.config.tgc_version }}
        fi

        if [[ "$SIMULATOR" == "spike" ]]
        then
            ./scripts/download_spike.sh $INSTALL_DIR/spike spike ${{ matrix.config.spike_version }}
            ./scripts/download_spike.sh $INSTALL_DIR/pk pk ${{ matrix.config.gnu_version }} ${{ matrix.config.arch }}_${{ matrix.config.abi }} ${{ matrix.config.gnu_name }}
            # ./scripts/setup_spike.sh $INSTALL_DIR/spike ${{ matrix.config.spike_version }}
            # ./scripts/setup_pk.sh $INSTALL_DIR/pk ${{ matrix.config.arch }} ${{ matrix.config.abi }} ${{ matrix.config.gnu_name }}
        fi

        if [[ "$SIMULATOR" == "spike_bm" ]]
        then
            ./scripts/download_spike.sh $INSTALL_DIR/spike spike ${{ matrix.config.spike_version }}
            ./scripts/download_spike.sh $INSTALL_DIR/htif htif ${{ matrix.config.gnu_version }} ${{ matrix.config.arch }}_${{ matrix.config.abi }} ${{ matrix.config.gnu_name }}
            # ./scripts/setup_spike.sh $INSTALL_DIR/spike ${{ matrix.config.spike_version }}
            # ./scripts/setup_htif.sh $INSTALL_DIR/htif ${{ matrix.config.arch }} ${{ matrix.config.abi }} ${{ matrix.config.gnu_name }}
        fi
    - name: Run Coremark example
      working-directory: examples/standalone/coremark
      run: |
        source $VENV_DIR/bin/activate
        make all
    - name: Archive reports
      uses: actions/upload-artifact@v4
      with:
        name: results-${{ matrix.toolchain }}-${{ matrix.simulator }}-${{ matrix.full }}
        path: |
          ${{ env.OUT_DIR }}/*.pdf
          ${{ env.OUT_DIR }}/*.out
          !${{ env.OUT_DIR }}/sess/elf
          !${{ env.OUT_DIR }}/sess/instr_trace
